name: Regression Testing
run-name: Regression tests run by ${{ github.actor }}
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "doc/**"
  pull_request:
  workflow_dispatch:
jobs:
  regression-testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Download Verus
        uses: actions/checkout@v2
        with:
          repository: verus-lang/verus
          path: verus
      - name: Build Verus
        run: |
          cd verus/source
          ./tools/get-z3.sh
          source ../tools/activate
          vargo build --release
      - name: Build simple controller
        run: VERUS_DIR=$PWD/verus ./build.sh simple_controller.rs --time
